swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v0
schemes:
  - https
tags:
  - name: Macro
    description: Everything about your Macro
paths:
  /Macro:
    tags:
      - Macro
    get:
      summary: Returns a list of macros.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
definitions:
  Macro:
    properties:
      id:
        type: integer
      protein:
        type: integer
      fats:
        type: integer
      carbs:
        type: integer
